### ISSUE TITLE
Datepicker Popup location error

### ISSUE THREAD

**Issue by ajiragroup** [kanakinfo/nepali_calendar#1]
In child table, Both BS and AD dates are shown. This is ok.

When clicked on child table date field, the date picker appears on top left.

See ss:

![image](https://github.com/user-attachments/assets/122a86e9-cd6a-4d80-b4a6-5407a7b775ec)

When clicked next time, datepicker location is correct.
![image](https://github.com/user-attachments/assets/49c4fd37-8885-4e0f-b9c9-e2d73d504fd7)

But Only one date (either AD or BS) is now shown.

**Comment by dka-kanak** [comment]
hi @ajiragroup now fixed 
get latest pull then check 
thanks
