### ISSUE TITLE
Date field does not respect Date settings.

### ISSUE THREAD

**Issue by ajiragroup** [kanakinfo/nepali_calendar#2]
This is my date settings:
![image](https://github.com/user-attachments/assets/9c254b81-0d33-4696-9e51-d4eba98d2e3c)

Date display:
![image](https://github.com/user-attachments/assets/2ede8aeb-baa7-4567-be06-bcca74fe13fe)

**Comment by dka-kanak** [comment]
hello @ajiragroup
its already work.
nepali date picker format setting save than refresh page becuase some old value in caches.
so need to first time refresh then check
<img width="800" alt="YYYY-MM-DD" src="https://github.com/user-attachments/assets/8be8e38d-fab4-4027-94ee-d0c0332f07a5">

thanks
