### ISSUE TITLE
Print (pdf) does not display Nepali Date

### ISSUE THREAD

**Issue by ajiragroup** [kanakinfo/nepali_calendar#3]
The form field shows Nepali date.

When printing, the Print format doesnot show Nepali date.

![image](https://github.com/user-attachments/assets/003e1ef4-48a7-4e44-a0e4-847e4f5a74ab)
![image](https://github.com/user-attachments/assets/fbcd39ce-946a-4557-9f8f-162b4abeb634)

**Comment by dka-kanak** [comment]
hello @ajiragroup now fixed 
please get latest pull then check
thanks
<img width="1115" alt="Untitled" src="https://github.com/user-attachments/assets/3d9f2037-d3e7-4da7-a286-a61fe69a911a">
<img width="1115" alt="Untitled1" src="https://github.com/user-attachments/assets/a6fab8d1-a589-4667-8b83-cafedb81d90f">

**Comment by ajiragroup** [comment]
Hi, thats great. We will check again. One quick question. Are you willing to take this app into next level ? If yes, we are ready to contribute. We will be giving ideas, logic, for integrating the app deep level in to Frappe not just as date converter and help in testing. Can't help in coding. If interested, please reach out to support@ajiragroup.com.
